INSERT INTO CUSTOMER (ID, TITLE, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL_ADDRESS)
VALUES (1, 'Mr', 'Waylon', 'Smithers', '1954-12-25', 'smithers@springfieldnuclear.com');

INSERT INTO PHYSICAL_ADDRESS (CUSTOMER, LINE1, CITY, POST_CODE, COUNTRY)
VALUES (1, '1000 Mammon Lane', 'Springfield', '80085', 'US');

INSERT INTO TAG (CUSTOMER, TAG)
VALUES (1, 'soppy');

INSERT INTO FAVORITE (CUSTOMER, CUSTOMER_KEY, THING, RATING)
VALUES(1, 1, 'Mr Burns', 'SUCKS');

INSERT INTO FAVORITE (CUSTOMER, CUSTOMER_KEY, THING, RATING)
VALUES(1, 0, 'Ice cream', 'AWESOME');
