spring:
  application:
    name: spring-boot-playground-webmvc
  main:
    banner-mode: "off"
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE

server:
  port: 10000
  shutdown: graceful
