DROP TABLE IF EXISTS FAVORITE;
DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS PHYSICAL_ADDRESS;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE         VARCHAR(20),
    FIRST_NAME    VARCHAR(255),
    LAST_NAME     VARCHAR(255),
    DATE_OF_BIRTH DATE,
    EMAIL_ADDRESS VARCHAR(255)
);

CREATE TABLE PHYSICAL_ADDRESS
(
    CUSTOMER  BIGINT PRIMARY KEY,
    LINE1     VARCHAR(255),
    LINE2     VARCHAR(255),
    CITY      VARCHAR(255),
    POST_CODE VARCHAR(255),
    COUNTRY   VARCHAR(2),
    CONSTRAINT FK_PHYSICAL_ADDRESS_CUSTOMER FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER (ID)
);

CREATE TABLE TAG
(
    CUSTOMER BIGINT,
    TAG      VARCHAR(255),
    CONSTRAINT PK_TAG PRIMARY KEY (CUSTOMER, TAG),
    CONSTRAINT FK_TAG_CUSTOMER FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER (ID)
);

CREATE TABLE FAVORITE
(
    CUSTOMER     BIGINT,
    CUSTOMER_KEY INT,
    THING        VARCHAR(255),
    RATING       VARCHAR(255),
    CONSTRAINT PK_FAVORITE PRIMARY KEY (CUSTOMER, CUSTOMER_KEY),
    CONSTRAINT FK_FAVORITE_CUSTOMER FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER (ID)
);
